name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - use: action/checkout 
      - run: docker compose build web_houses_api
      - run: docker tag web_houses_api lorislin/web_houses_api:latest
      - run: docker login -u lorisl
      - run: docker push lorislin/web_houses_api:latest
      - run: ssh ubuntu@17.2.2.1 "docker compose pull lorislin/web_houses_api:latest"
      - rn: "(re)start container"