name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t lorisl/web_houses_api:latest .
      - run: docker tag lorisl/web_houses_api lorisl/web_houses_api:latest
      - run: docker login -u "lorisl" -p "${{ secrets.LOGIN_SECRET }}"
      - run: docker push lorisl/web_houses_api:latest
      - run: sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ssh ubuntu@20.86.55.5 "docker compose pull lorisl/web_houses_api:latest"
      - run: docker compose down | docker compose up -d
