name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker compose build lorislin/web_houses_api
      - run: docker tag lorislin/web_houses_api lorislin/web_houses_api
      - run: docker login -u "lorisl" -p "${{ secrets.LOGIN_SECRET }}"
      - run: docker push lorislin/web_houses_api:latest
      - run: ssh ubuntu@20.86.55.5 "docker compose pull lorislin/web_houses_api:latest"
      - run: docker compose down | docker compose up -d
